// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
	"io"
)

type GetJobsDocumentsDocumentIDRequest struct {
	DocumentID string `pathParam:"style=simple,explode=false,name=documentId"`
}

func (g *GetJobsDocumentsDocumentIDRequest) GetDocumentID() string {
	if g == nil {
		return ""
	}
	return g.DocumentID
}

type GetJobsDocumentsDocumentIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationJSONResponseStream io.ReadCloser
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredTextJSONResponseStream io.ReadCloser
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationJSONPlusEncryptedResponseStream io.ReadCloser
}

func (g *GetJobsDocumentsDocumentIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetJobsDocumentsDocumentIDResponse) GetTwoHundredApplicationJSONResponseStream() io.ReadCloser {
	if g == nil {
		return nil
	}
	return g.TwoHundredApplicationJSONResponseStream
}

func (g *GetJobsDocumentsDocumentIDResponse) GetTwoHundredTextJSONResponseStream() io.ReadCloser {
	if g == nil {
		return nil
	}
	return g.TwoHundredTextJSONResponseStream
}

func (g *GetJobsDocumentsDocumentIDResponse) GetTwoHundredApplicationJSONPlusEncryptedResponseStream() io.ReadCloser {
	if g == nil {
		return nil
	}
	return g.TwoHundredApplicationJSONPlusEncryptedResponseStream
}
