// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type GetJobsJobGUIDDocumentsRequest struct {
	JobGUID string `pathParam:"style=simple,explode=false,name=jobGuid"`
}

func (g *GetJobsJobGUIDDocumentsRequest) GetJobGUID() string {
	if g == nil {
		return ""
	}
	return g.JobGUID
}

type GetJobsJobGUIDDocumentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DocumentListResponse *components.DocumentListResponse
}

func (g *GetJobsJobGUIDDocumentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetJobsJobGUIDDocumentsResponse) GetDocumentListResponse() *components.DocumentListResponse {
	if g == nil {
		return nil
	}
	return g.DocumentListResponse
}
