// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type GetJobsJobIDStatusRequest struct {
	JobID string `pathParam:"style=simple,explode=false,name=jobId"`
}

func (g *GetJobsJobIDStatusRequest) GetJobID() string {
	if g == nil {
		return ""
	}
	return g.JobID
}

type GetJobsJobIDStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	JobStatusResponse *components.JobStatusResponse
}

func (g *GetJobsJobIDStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetJobsJobIDStatusResponse) GetJobStatusResponse() *components.JobStatusResponse {
	if g == nil {
		return nil
	}
	return g.JobStatusResponse
}
