// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type GetJobsJobIDRequest struct {
	JobID string `pathParam:"style=simple,explode=false,name=jobId"`
}

func (g *GetJobsJobIDRequest) GetJobID() string {
	if g == nil {
		return ""
	}
	return g.JobID
}

type GetJobsJobIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	JobDetailsResponse *components.JobDetailsResponse
}

func (g *GetJobsJobIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetJobsJobIDResponse) GetJobDetailsResponse() *components.JobDetailsResponse {
	if g == nil {
		return nil
	}
	return g.JobDetailsResponse
}
