// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type GetJobsJobIDAllRequest struct {
	JobID string `pathParam:"style=simple,explode=false,name=jobId"`
}

func (g *GetJobsJobIDAllRequest) GetJobID() string {
	if g == nil {
		return ""
	}
	return g.JobID
}

type GetJobsJobIDAllResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	JobArtifactsResponse *components.JobArtifactsResponse
}

func (g *GetJobsJobIDAllResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetJobsJobIDAllResponse) GetJobArtifactsResponse() *components.JobArtifactsResponse {
	if g == nil {
		return nil
	}
	return g.JobArtifactsResponse
}
