// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type GetTestAPIKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (g *GetTestAPIKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}
