// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LinkClientInfoResponse *components.LinkClientInfoResponse
}

func (o *PostLinkInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostLinkInfoResponse) GetLinkClientInfoResponse() *components.LinkClientInfoResponse {
	if o == nil {
		return nil
	}
	return o.LinkClientInfoResponse
}
