// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostConnectionContextResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ConnectionContextResponse *components.ConnectionContextResponse
}

func (o *PostConnectionContextResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostConnectionContextResponse) GetConnectionContextResponse() *components.ConnectionContextResponse {
	if o == nil {
		return nil
	}
	return o.ConnectionContextResponse
}
