// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostWebhookSubscriptionsSubscriptionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TwoHundredApplicationJSONWebhookSubscriptionResponses []components.WebhookSubscriptionResponse
	// OK
	TwoHundredTextJSONWebhookSubscriptionResponses []components.WebhookSubscriptionResponse
	// OK
	TwoHundredApplicationJSONPlusEncryptedWebhookSubscriptionResponses []components.WebhookSubscriptionResponse
}

func (p *PostWebhookSubscriptionsSubscriptionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostWebhookSubscriptionsSubscriptionsResponse) GetTwoHundredApplicationJSONWebhookSubscriptionResponses() []components.WebhookSubscriptionResponse {
	if p == nil {
		return nil
	}
	return p.TwoHundredApplicationJSONWebhookSubscriptionResponses
}

func (p *PostWebhookSubscriptionsSubscriptionsResponse) GetTwoHundredTextJSONWebhookSubscriptionResponses() []components.WebhookSubscriptionResponse {
	if p == nil {
		return nil
	}
	return p.TwoHundredTextJSONWebhookSubscriptionResponses
}

func (p *PostWebhookSubscriptionsSubscriptionsResponse) GetTwoHundredApplicationJSONPlusEncryptedWebhookSubscriptionResponses() []components.WebhookSubscriptionResponse {
	if p == nil {
		return nil
	}
	return p.TwoHundredApplicationJSONPlusEncryptedWebhookSubscriptionResponses
}
