// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostJobsMfaAnswerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PostJobsMfaAnswerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
