// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkAuthenticationMfaAnswerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (p *PostLinkAuthenticationMfaAnswerResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}
