// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
	"io"
)

type PostJobsDocumentsFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationJSONResponseStream io.ReadCloser
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredTextJSONResponseStream io.ReadCloser
}

func (o *PostJobsDocumentsFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostJobsDocumentsFileResponse) GetTwoHundredApplicationJSONResponseStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONResponseStream
}

func (o *PostJobsDocumentsFileResponse) GetTwoHundredTextJSONResponseStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextJSONResponseStream
}
