// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostJobsDocumentsListRequest struct {
	JobGUID            *string                        `queryParam:"style=form,explode=true,name=job_guid"`
	AccessTokenRequest *components.AccessTokenRequest `request:"mediaType=application/json"`
}

func (p *PostJobsDocumentsListRequest) GetJobGUID() *string {
	if p == nil {
		return nil
	}
	return p.JobGUID
}

func (p *PostJobsDocumentsListRequest) GetAccessTokenRequest() *components.AccessTokenRequest {
	if p == nil {
		return nil
	}
	return p.AccessTokenRequest
}

type PostJobsDocumentsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DocumentListResponse *components.DocumentListResponse
}

func (p *PostJobsDocumentsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostJobsDocumentsListResponse) GetDocumentListResponse() *components.DocumentListResponse {
	if p == nil {
		return nil
	}
	return p.DocumentListResponse
}
