// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkTokenGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LinkTokenGetResponse *components.LinkTokenGetResponse
}

func (o *PostLinkTokenGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostLinkTokenGetResponse) GetLinkTokenGetResponse() *components.LinkTokenGetResponse {
	if o == nil {
		return nil
	}
	return o.LinkTokenGetResponse
}
