// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostConnectionAccessTokenInvalidateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	InvalidateAccessTokenResponse *components.InvalidateAccessTokenResponse
}

func (p *PostConnectionAccessTokenInvalidateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostConnectionAccessTokenInvalidateResponse) GetInvalidateAccessTokenResponse() *components.InvalidateAccessTokenResponse {
	if p == nil {
		return nil
	}
	return p.InvalidateAccessTokenResponse
}
