// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostWebhookSubscriptionsSubscriptionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TwoHundredApplicationJSONWebhookSubscriptionResponses []components.WebhookSubscriptionResponse
	// OK
	TwoHundredTextJSONWebhookSubscriptionResponses []components.WebhookSubscriptionResponse
	// OK
	TwoHundredApplicationJSONPlusEncryptedWebhookSubscriptionResponses []components.WebhookSubscriptionResponse
}

func (o *PostWebhookSubscriptionsSubscriptionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostWebhookSubscriptionsSubscriptionsResponse) GetTwoHundredApplicationJSONWebhookSubscriptionResponses() []components.WebhookSubscriptionResponse {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONWebhookSubscriptionResponses
}

func (o *PostWebhookSubscriptionsSubscriptionsResponse) GetTwoHundredTextJSONWebhookSubscriptionResponses() []components.WebhookSubscriptionResponse {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextJSONWebhookSubscriptionResponses
}

func (o *PostWebhookSubscriptionsSubscriptionsResponse) GetTwoHundredApplicationJSONPlusEncryptedWebhookSubscriptionResponses() []components.WebhookSubscriptionResponse {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONPlusEncryptedWebhookSubscriptionResponses
}
