// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkAccountListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LinkAccountListResponse *components.LinkAccountListResponse
}

func (p *PostLinkAccountListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostLinkAccountListResponse) GetLinkAccountListResponse() *components.LinkAccountListResponse {
	if p == nil {
		return nil
	}
	return p.LinkAccountListResponse
}
