// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostConnectionPublicTokenExchangeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ConnectionPublicTokenExchangeResponse *components.ConnectionPublicTokenExchangeResponse
}

func (p *PostConnectionPublicTokenExchangeResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostConnectionPublicTokenExchangeResponse) GetConnectionPublicTokenExchangeResponse() *components.ConnectionPublicTokenExchangeResponse {
	if p == nil {
		return nil
	}
	return p.ConnectionPublicTokenExchangeResponse
}
