// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostJobsSubmitRequestBody2 struct {
	// The job type identifier
	JobCode string `json:"job_code"`
	// Dynamic input object - structure varies by job type
	Input map[string]string `json:"input"`
}

func (o *PostJobsSubmitRequestBody2) GetJobCode() string {
	if o == nil {
		return ""
	}
	return o.JobCode
}

func (o *PostJobsSubmitRequestBody2) GetInput() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Input
}

type PostJobsSubmitRequest struct {
	// Can be used against the sandbox API with special values to test error use cases
	XDeckSandbox *string                     `header:"style=simple,explode=false,name=x-deck-sandbox"`
	RequestBody  *PostJobsSubmitRequestBody2 `request:"mediaType=application/json"`
}

func (o *PostJobsSubmitRequest) GetXDeckSandbox() *string {
	if o == nil {
		return nil
	}
	return o.XDeckSandbox
}

func (o *PostJobsSubmitRequest) GetRequestBody() *PostJobsSubmitRequestBody2 {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type PostJobsSubmitResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	JobResponse *components.JobResponse
}

func (o *PostJobsSubmitResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostJobsSubmitResponse) GetJobResponse() *components.JobResponse {
	if o == nil {
		return nil
	}
	return o.JobResponse
}
