// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostConnectionAccountsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetConnectionAccountsResponse *components.GetConnectionAccountsResponse
}

func (o *PostConnectionAccountsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostConnectionAccountsResponse) GetGetConnectionAccountsResponse() *components.GetConnectionAccountsResponse {
	if o == nil {
		return nil
	}
	return o.GetConnectionAccountsResponse
}
