// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
	"io"
)

type PostJobsDocumentsFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationJSONResponseStream io.ReadCloser
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredTextJSONResponseStream io.ReadCloser
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationJSONPlusEncryptedResponseStream io.ReadCloser
}

func (p *PostJobsDocumentsFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostJobsDocumentsFileResponse) GetTwoHundredApplicationJSONResponseStream() io.ReadCloser {
	if p == nil {
		return nil
	}
	return p.TwoHundredApplicationJSONResponseStream
}

func (p *PostJobsDocumentsFileResponse) GetTwoHundredTextJSONResponseStream() io.ReadCloser {
	if p == nil {
		return nil
	}
	return p.TwoHundredTextJSONResponseStream
}

func (p *PostJobsDocumentsFileResponse) GetTwoHundredApplicationJSONPlusEncryptedResponseStream() io.ReadCloser {
	if p == nil {
		return nil
	}
	return p.TwoHundredApplicationJSONPlusEncryptedResponseStream
}
