// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostConnectionContextResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ConnectionContextResponse *components.ConnectionContextResponse
}

func (p *PostConnectionContextResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostConnectionContextResponse) GetConnectionContextResponse() *components.ConnectionContextResponse {
	if p == nil {
		return nil
	}
	return p.ConnectionContextResponse
}
