// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkConnectionStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LinkConnectionStatusResponse *components.LinkConnectionStatusResponse
}

func (p *PostLinkConnectionStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostLinkConnectionStatusResponse) GetLinkConnectionStatusResponse() *components.LinkConnectionStatusResponse {
	if p == nil {
		return nil
	}
	return p.LinkConnectionStatusResponse
}
