// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostConnectionAccountsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetConnectionAccountsResponse *components.GetConnectionAccountsResponse
}

func (p *PostConnectionAccountsResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostConnectionAccountsResponse) GetGetConnectionAccountsResponse() *components.GetConnectionAccountsResponse {
	if p == nil {
		return nil
	}
	return p.GetConnectionAccountsResponse
}
