// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostWebhookSubscriptionsEventTypesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	WebhookEventTypesResponse *components.WebhookEventTypesResponse
}

func (o *PostWebhookSubscriptionsEventTypesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostWebhookSubscriptionsEventTypesResponse) GetWebhookEventTypesResponse() *components.WebhookEventTypesResponse {
	if o == nil {
		return nil
	}
	return o.WebhookEventTypesResponse
}
