// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkConnectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LinkConnectResponse *components.LinkConnectResponse
}

func (p *PostLinkConnectResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostLinkConnectResponse) GetLinkConnectResponse() *components.LinkConnectResponse {
	if p == nil {
		return nil
	}
	return p.LinkConnectResponse
}
