// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostJobsJobGUIDCancelRequest struct {
	JobGUID string `pathParam:"style=simple,explode=false,name=jobGuid"`
}

func (p *PostJobsJobGUIDCancelRequest) GetJobGUID() string {
	if p == nil {
		return ""
	}
	return p.JobGUID
}

type PostJobsJobGUIDCancelResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	JobCancelResponse *components.JobCancelResponse
}

func (p *PostJobsJobGUIDCancelResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostJobsJobGUIDCancelResponse) GetJobCancelResponse() *components.JobCancelResponse {
	if p == nil {
		return nil
	}
	return p.JobCancelResponse
}
