// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkAuthenticationMfaGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SecurityQuestionResponse *components.SecurityQuestionResponse
}

func (p *PostLinkAuthenticationMfaGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostLinkAuthenticationMfaGetResponse) GetSecurityQuestionResponse() *components.SecurityQuestionResponse {
	if p == nil {
		return nil
	}
	return p.SecurityQuestionResponse
}
