// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkSourcesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LinkSourcesResponse *components.LinkSourcesResponse
}

func (p *PostLinkSourcesResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostLinkSourcesResponse) GetLinkSourcesResponse() *components.LinkSourcesResponse {
	if p == nil {
		return nil
	}
	return p.LinkSourcesResponse
}
