// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkTokenCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LinkTokenRequestResponse *components.LinkTokenRequestResponse
}

func (p *PostLinkTokenCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostLinkTokenCreateResponse) GetLinkTokenRequestResponse() *components.LinkTokenRequestResponse {
	if p == nil {
		return nil
	}
	return p.LinkTokenRequestResponse
}
