// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/buildwithdeck/sdk-go/models/components"
)

type PostLinkAccountListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LinkAccountListResponse *components.LinkAccountListResponse
}

func (o *PostLinkAccountListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostLinkAccountListResponse) GetLinkAccountListResponse() *components.LinkAccountListResponse {
	if o == nil {
		return nil
	}
	return o.LinkAccountListResponse
}
