// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AccountSelectModeEnum string

const (
	AccountSelectModeEnumAll      AccountSelectModeEnum = "All"
	AccountSelectModeEnumSingle   AccountSelectModeEnum = "Single"
	AccountSelectModeEnumMultiple AccountSelectModeEnum = "Multiple"
)

func (e AccountSelectModeEnum) ToPointer() *AccountSelectModeEnum {
	return &e
}
func (e *AccountSelectModeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "All":
		fallthrough
	case "Single":
		fallthrough
	case "Multiple":
		*e = AccountSelectModeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountSelectModeEnum: %v", v)
	}
}
