// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AutoRefreshUpdateRequest struct {
	// The access token associated with the Item data is being requested for
	AccessToken string `json:"access_token"`
	// Flag to toggle the automatic refresh when new connection's data is found
	AutoRefresh bool `json:"auto_refresh"`
}

func (a *AutoRefreshUpdateRequest) GetAccessToken() string {
	if a == nil {
		return ""
	}
	return a.AccessToken
}

func (a *AutoRefreshUpdateRequest) GetAutoRefresh() bool {
	if a == nil {
		return false
	}
	return a.AutoRefresh
}
