// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConnectionPublicTokenExchangeResponse struct {
	// The access token associated with the connection data is being requested for
	AccessToken *string `json:"access_token,omitempty"`
	// The Deck Connection ID for the connection associated with the returned access token
	ConnectionID *string `json:"connection_id,omitempty"`
	// List of non-sensitive values provided from the Link session by the user
	Fields []LinkConnectRequestField `json:"fields"`
}

func (o *ConnectionPublicTokenExchangeResponse) GetAccessToken() *string {
	if o == nil {
		return nil
	}
	return o.AccessToken
}

func (o *ConnectionPublicTokenExchangeResponse) GetConnectionID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionID
}

func (o *ConnectionPublicTokenExchangeResponse) GetFields() []LinkConnectRequestField {
	if o == nil {
		return []LinkConnectRequestField{}
	}
	return o.Fields
}
