// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConnectionPublicTokenExchangeRequest struct {
	// Your public_token, obtained from the Link onSuccess callback
	PublicToken string `json:"public_token"`
}

func (c *ConnectionPublicTokenExchangeRequest) GetPublicToken() string {
	if c == nil {
		return ""
	}
	return c.PublicToken
}
