// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/buildwithdeck/sdk-go/internal/utils"
	"time"
)

type ConnectionContextResponse struct {
	// The Deck Connection ID associated with the access token data being requested
	ConnectionID *string `json:"connection_id,omitempty"`
	// The data source associated to this connectiond
	Provider Provider `json:"provider"`
	// Represents the current connection health status between the system and the data source, such as Connected or Disconnected.
	ConnectionStatus *ConnectivityStatusEnum `json:"connection_status,omitempty"`
	// The UTC timestamp of when the connectivity status was last updated.
	ConnectionStatusTimestamp *time.Time `json:"connection_status_timestamp,omitempty"`
	// Represents the most recent scraping result for this connection, providing additional context to the connectivity status.
	ConnectionStatusReason *ScrapingStatusEnum `json:"connection_status_reason,omitempty"`
	// Represents the number of accounts.
	NumOfEntities *int `json:"num_of_entities,omitempty"`
	// A list of entities associated with this connection.
	Entities []Entity `json:"entities"`
}

func (c ConnectionContextResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectionContextResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ConnectionContextResponse) GetConnectionID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionID
}

func (o *ConnectionContextResponse) GetProvider() Provider {
	if o == nil {
		return Provider{}
	}
	return o.Provider
}

func (o *ConnectionContextResponse) GetConnectionStatus() *ConnectivityStatusEnum {
	if o == nil {
		return nil
	}
	return o.ConnectionStatus
}

func (o *ConnectionContextResponse) GetConnectionStatusTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.ConnectionStatusTimestamp
}

func (o *ConnectionContextResponse) GetConnectionStatusReason() *ScrapingStatusEnum {
	if o == nil {
		return nil
	}
	return o.ConnectionStatusReason
}

func (o *ConnectionContextResponse) GetNumOfEntities() *int {
	if o == nil {
		return nil
	}
	return o.NumOfEntities
}

func (o *ConnectionContextResponse) GetEntities() []Entity {
	if o == nil {
		return []Entity{}
	}
	return o.Entities
}
