// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DocumentListResponse struct {
	Documents []DocumentInfo `json:"documents"`
}

func (o *DocumentListResponse) GetDocuments() []DocumentInfo {
	if o == nil {
		return []DocumentInfo{}
	}
	return o.Documents
}
