// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DocumentListResponse struct {
	Documents []DocumentInfo `json:"documents"`
}

func (d *DocumentListResponse) GetDocuments() []DocumentInfo {
	if d == nil {
		return []DocumentInfo{}
	}
	return d.Documents
}
