// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Entity struct {
	AccountNumber string `json:"account_number"`
}

func (e *Entity) GetAccountNumber() string {
	if e == nil {
		return ""
	}
	return e.AccountNumber
}
