// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Entity struct {
	AccountNumber string `json:"account_number"`
}

func (o *Entity) GetAccountNumber() string {
	if o == nil {
		return ""
	}
	return o.AccountNumber
}
