// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type FieldTypeEnum string

const (
	FieldTypeEnumText     FieldTypeEnum = "Text"
	FieldTypeEnumPassword FieldTypeEnum = "Password"
)

func (e FieldTypeEnum) ToPointer() *FieldTypeEnum {
	return &e
}
func (e *FieldTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Text":
		fallthrough
	case "Password":
		*e = FieldTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FieldTypeEnum: %v", v)
	}
}
