// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetConnectionAccountsResponseAccount struct {
	AccountNumber string `json:"account_number"`
	IsSelected    bool   `json:"is_selected"`
}

func (o *GetConnectionAccountsResponseAccount) GetAccountNumber() string {
	if o == nil {
		return ""
	}
	return o.AccountNumber
}

func (o *GetConnectionAccountsResponseAccount) GetIsSelected() bool {
	if o == nil {
		return false
	}
	return o.IsSelected
}
