// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetConnectionAccountsResponse struct {
	Accounts []GetConnectionAccountsResponseAccount `json:"accounts,omitempty"`
}

func (o *GetConnectionAccountsResponse) GetAccounts() []GetConnectionAccountsResponseAccount {
	if o == nil {
		return nil
	}
	return o.Accounts
}
