// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetConnectionAccountsResponse struct {
	Accounts []GetConnectionAccountsResponseAccount `json:"accounts,omitempty"`
}

func (g *GetConnectionAccountsResponse) GetAccounts() []GetConnectionAccountsResponseAccount {
	if g == nil {
		return nil
	}
	return g.Accounts
}
