// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetConnectionAccountsResponseAccount struct {
	AccountNumber string `json:"account_number"`
	IsSelected    bool   `json:"is_selected"`
}

func (g *GetConnectionAccountsResponseAccount) GetAccountNumber() string {
	if g == nil {
		return ""
	}
	return g.AccountNumber
}

func (g *GetConnectionAccountsResponseAccount) GetIsSelected() bool {
	if g == nil {
		return false
	}
	return g.IsSelected
}
