// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetConnectionAccountsRequestAccount struct {
	AccountNumber *string `json:"account_number"`
	IsSelected    bool    `json:"is_selected"`
}

func (o *GetConnectionAccountsRequestAccount) GetAccountNumber() *string {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *GetConnectionAccountsRequestAccount) GetIsSelected() bool {
	if o == nil {
		return false
	}
	return o.IsSelected
}
