// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetConnectionAccountsRequestAccount struct {
	AccountNumber *string `json:"account_number"`
	IsSelected    bool    `json:"is_selected"`
}

func (g *GetConnectionAccountsRequestAccount) GetAccountNumber() *string {
	if g == nil {
		return nil
	}
	return g.AccountNumber
}

func (g *GetConnectionAccountsRequestAccount) GetIsSelected() bool {
	if g == nil {
		return false
	}
	return g.IsSelected
}
