// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IJobResponse struct {
	JobGUID *string `json:"job_guid,omitempty"`
	JobCode *string `json:"job_code,omitempty"`
}

func (o *IJobResponse) GetJobGUID() *string {
	if o == nil {
		return nil
	}
	return o.JobGUID
}

func (o *IJobResponse) GetJobCode() *string {
	if o == nil {
		return nil
	}
	return o.JobCode
}
