// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IJobResponse struct {
	JobGUID *string `json:"job_guid,omitempty"`
	JobCode *string `json:"job_code,omitempty"`
}

func (i *IJobResponse) GetJobGUID() *string {
	if i == nil {
		return nil
	}
	return i.JobGUID
}

func (i *IJobResponse) GetJobCode() *string {
	if i == nil {
		return nil
	}
	return i.JobCode
}
