// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InvalidateAccessTokenResponse struct {
	// The access token associated with the connection data being requested
	NewAccessToken *string `json:"new_access_token,omitempty"`
}

func (o *InvalidateAccessTokenResponse) GetNewAccessToken() *string {
	if o == nil {
		return nil
	}
	return o.NewAccessToken
}
