// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobArtifactsResponse struct {
	// The unique identifier of the job.
	JobID string `json:"job_id"`
	// The status of the job executed.
	Status JobStatus `json:"status"`
	// The status of the job executed.
	Output *string `json:"output,omitempty"`
	// The source against which the job executed.
	Source SourceData `json:"source"`
	// The artifacts that have been compiled during a job execution.
	Artifacts *JobArtifactData `json:"artifacts,omitempty"`
	// The time the job execution was created.
	CreatedAt int64 `json:"created_at"`
	// The time the job execution was updated.
	UpdatedAt int64 `json:"updated_at"`
}

func (j *JobArtifactsResponse) GetJobID() string {
	if j == nil {
		return ""
	}
	return j.JobID
}

func (j *JobArtifactsResponse) GetStatus() JobStatus {
	if j == nil {
		return JobStatus("")
	}
	return j.Status
}

func (j *JobArtifactsResponse) GetOutput() *string {
	if j == nil {
		return nil
	}
	return j.Output
}

func (j *JobArtifactsResponse) GetSource() SourceData {
	if j == nil {
		return SourceData{}
	}
	return j.Source
}

func (j *JobArtifactsResponse) GetArtifacts() *JobArtifactData {
	if j == nil {
		return nil
	}
	return j.Artifacts
}

func (j *JobArtifactsResponse) GetCreatedAt() int64 {
	if j == nil {
		return 0
	}
	return j.CreatedAt
}

func (j *JobArtifactsResponse) GetUpdatedAt() int64 {
	if j == nil {
		return 0
	}
	return j.UpdatedAt
}
