// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobArtifactData struct {
	Screenshots []ScreenshotData `json:"screenshots,omitempty"`
}

func (j *JobArtifactData) GetScreenshots() []ScreenshotData {
	if j == nil {
		return nil
	}
	return j.Screenshots
}
