// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobCancelResponse struct {
	JobGUID   *string    `json:"job_guid,omitempty"`
	Status    *JobStatus `json:"status,omitempty"`
	CreatedAt int64      `json:"created_at"`
	UpdatedAt int64      `json:"updated_at"`
}

func (j *JobCancelResponse) GetJobGUID() *string {
	if j == nil {
		return nil
	}
	return j.JobGUID
}

func (j *JobCancelResponse) GetStatus() *JobStatus {
	if j == nil {
		return nil
	}
	return j.Status
}

func (j *JobCancelResponse) GetCreatedAt() int64 {
	if j == nil {
		return 0
	}
	return j.CreatedAt
}

func (j *JobCancelResponse) GetUpdatedAt() int64 {
	if j == nil {
		return 0
	}
	return j.UpdatedAt
}
