// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobDetailsResponse struct {
	// The unique identifier of the job.
	JobID string `json:"job_id"`
	// The code representing the type of job executed.
	JobCode string `json:"job_code"`
	// The status of the job executed.
	Status JobStatus `json:"status"`
	// The status of the job executed.
	Output *string `json:"output,omitempty"`
	// The identifier of the source against which the job executed.
	SourceID string `json:"source_id"`
	// The name of the source against which the job executed.
	SourceName string `json:"source_name"`
	// The time the job execution was created.
	CreatedAt int64 `json:"created_at"`
	// The time the job execution was updated.
	UpdatedAt int64 `json:"updated_at"`
}

func (j *JobDetailsResponse) GetJobID() string {
	if j == nil {
		return ""
	}
	return j.JobID
}

func (j *JobDetailsResponse) GetJobCode() string {
	if j == nil {
		return ""
	}
	return j.JobCode
}

func (j *JobDetailsResponse) GetStatus() JobStatus {
	if j == nil {
		return JobStatus("")
	}
	return j.Status
}

func (j *JobDetailsResponse) GetOutput() *string {
	if j == nil {
		return nil
	}
	return j.Output
}

func (j *JobDetailsResponse) GetSourceID() string {
	if j == nil {
		return ""
	}
	return j.SourceID
}

func (j *JobDetailsResponse) GetSourceName() string {
	if j == nil {
		return ""
	}
	return j.SourceName
}

func (j *JobDetailsResponse) GetCreatedAt() int64 {
	if j == nil {
		return 0
	}
	return j.CreatedAt
}

func (j *JobDetailsResponse) GetUpdatedAt() int64 {
	if j == nil {
		return 0
	}
	return j.UpdatedAt
}
