// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobResponse struct {
	// The unique identifier of the job.
	JobGUID string `json:"job_guid"`
	// The code representing the type of job executed.
	JobCode string `json:"job_code"`
}

func (o *JobResponse) GetJobGUID() string {
	if o == nil {
		return ""
	}
	return o.JobGUID
}

func (o *JobResponse) GetJobCode() string {
	if o == nil {
		return ""
	}
	return o.JobCode
}
