// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type JobStatus string

const (
	JobStatusRunning   JobStatus = "Running"
	JobStatusFailed    JobStatus = "Failed"
	JobStatusCompleted JobStatus = "Completed"
	JobStatusCanceled  JobStatus = "Canceled"
)

func (e JobStatus) ToPointer() *JobStatus {
	return &e
}
func (e *JobStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Running":
		fallthrough
	case "Failed":
		fallthrough
	case "Completed":
		fallthrough
	case "Canceled":
		*e = JobStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobStatus: %v", v)
	}
}
