// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkSourcesResponse struct {
	// List of data sources found.
	Sources []LinkSourcesResponseSource `json:"sources,omitempty"`
}

func (l *LinkSourcesResponse) GetSources() []LinkSourcesResponseSource {
	if l == nil {
		return nil
	}
	return l.Sources
}
