// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkSourcesResponseSource struct {
	// Unique identifier of the source with Datadeck.
	SourceID *string `json:"source_id,omitempty"`
	// Name of the data source.
	Name *string `json:"name,omitempty"`
	// Url to display the data source logo, when available (can be null).
	LogoURL *string `json:"logo_url,omitempty"`
	// Country code of the data source in ISO 3166 format (2 characters).
	Country *string `json:"country,omitempty"`
	// Website of the data source, useful for resetting a password.
	Website *string `json:"website,omitempty"`
	// The required fields to be displayed to the user for entering his credentials. In Update mode (for changing a password), the Username value of the connection being updated will also be provided, to be displayed in read-only.
	Fields []LinkSourcesResponseSourceField `json:"fields,omitempty"`
}

func (l *LinkSourcesResponseSource) GetSourceID() *string {
	if l == nil {
		return nil
	}
	return l.SourceID
}

func (l *LinkSourcesResponseSource) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LinkSourcesResponseSource) GetLogoURL() *string {
	if l == nil {
		return nil
	}
	return l.LogoURL
}

func (l *LinkSourcesResponseSource) GetCountry() *string {
	if l == nil {
		return nil
	}
	return l.Country
}

func (l *LinkSourcesResponseSource) GetWebsite() *string {
	if l == nil {
		return nil
	}
	return l.Website
}

func (l *LinkSourcesResponseSource) GetFields() []LinkSourcesResponseSourceField {
	if l == nil {
		return nil
	}
	return l.Fields
}
