// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkSourcesRequest struct {
	// The link_token, must be provided when calling Link endpoints, for identifying the Link session.
	LinkToken string `json:"link_token"`
	// The specific source identifier to find. If left to NULL, a list of the 15 most common data sources is returned. If specified, the search argument will be ignored.
	SourceID *string `json:"source_id,omitempty"`
	// A search term for filtering the list by data source name. If left to NULL or empty, a list of the 15 most common data sources is returned.
	Search *string `json:"search,omitempty"`
}

func (l *LinkSourcesRequest) GetLinkToken() string {
	if l == nil {
		return ""
	}
	return l.LinkToken
}

func (l *LinkSourcesRequest) GetSourceID() *string {
	if l == nil {
		return nil
	}
	return l.SourceID
}

func (l *LinkSourcesRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}
