// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkAccountListResponse struct {
	// List of available accounts
	Accounts []LinkAccountListResponseAccountItem `json:"accounts,omitempty"`
}

func (l *LinkAccountListResponse) GetAccounts() []LinkAccountListResponseAccountItem {
	if l == nil {
		return nil
	}
	return l.Accounts
}
