// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkAccountListResponse struct {
	// List of available accounts
	Accounts []LinkAccountListResponseAccountItem `json:"accounts,omitempty"`
}

func (o *LinkAccountListResponse) GetAccounts() []LinkAccountListResponseAccountItem {
	if o == nil {
		return nil
	}
	return o.Accounts
}
