// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkConnectRequestField struct {
	FieldName  string `json:"field_name"`
	FieldValue string `json:"field_value"`
}

func (l *LinkConnectRequestField) GetFieldName() string {
	if l == nil {
		return ""
	}
	return l.FieldName
}

func (l *LinkConnectRequestField) GetFieldValue() string {
	if l == nil {
		return ""
	}
	return l.FieldValue
}
