// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkSourcesResponseSourceField struct {
	FieldNumber int            `json:"field_number"`
	FieldName   string         `json:"field_name"`
	FieldLabel  string         `json:"field_label"`
	FieldValue  *string        `json:"field_value,omitempty"`
	FieldType   *FieldTypeEnum `json:"field_type,omitempty"`
}

func (o *LinkSourcesResponseSourceField) GetFieldNumber() int {
	if o == nil {
		return 0
	}
	return o.FieldNumber
}

func (o *LinkSourcesResponseSourceField) GetFieldName() string {
	if o == nil {
		return ""
	}
	return o.FieldName
}

func (o *LinkSourcesResponseSourceField) GetFieldLabel() string {
	if o == nil {
		return ""
	}
	return o.FieldLabel
}

func (o *LinkSourcesResponseSourceField) GetFieldValue() *string {
	if o == nil {
		return nil
	}
	return o.FieldValue
}

func (o *LinkSourcesResponseSourceField) GetFieldType() *FieldTypeEnum {
	if o == nil {
		return nil
	}
	return o.FieldType
}
