// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkConnectionStatusResponse struct {
	// The current status of the connection requested
	Status *LinkConnectionStatusResponseEnum `json:"status,omitempty"`
	// Additional information related to the status
	AdditionalInformation *string `json:"additional_information,omitempty"`
}

func (l *LinkConnectionStatusResponse) GetStatus() *LinkConnectionStatusResponseEnum {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *LinkConnectionStatusResponse) GetAdditionalInformation() *string {
	if l == nil {
		return nil
	}
	return l.AdditionalInformation
}
