// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkAccountSelectRequest struct {
	// The link_token, must be provided when calling Link endpoints, for identifying the Link session.
	LinkToken string `json:"link_token"`
	// List of selected accounts
	Accounts []string `json:"accounts,omitempty"`
}

func (o *LinkAccountSelectRequest) GetLinkToken() string {
	if o == nil {
		return ""
	}
	return o.LinkToken
}

func (o *LinkAccountSelectRequest) GetAccounts() []string {
	if o == nil {
		return nil
	}
	return o.Accounts
}
