// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkConnectResponse struct {
	// This token must be exchanged for an access_token. In Update mode for an existing connection, the public_token is not returned: There is no need to go through the process of exchanging a public_token for an access_token and the connection's existing access_token will not change.
	PublicToken *string `json:"public_token,omitempty"`
	// Used to identify a connection in webhooks.
	JobGUID *string `json:"job_guid,omitempty"`
}

func (l *LinkConnectResponse) GetPublicToken() *string {
	if l == nil {
		return nil
	}
	return l.PublicToken
}

func (l *LinkConnectResponse) GetJobGUID() *string {
	if l == nil {
		return nil
	}
	return l.JobGUID
}
