// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkAccountListResponseAccountItem struct {
	// The account identifier
	AccountID     *string `json:"account_id,omitempty"`
	AccountNumber *string `json:"account_number,omitempty"`
	// The account's address if available
	AccountAddress *string `json:"account_address,omitempty"`
}

func (l *LinkAccountListResponseAccountItem) GetAccountID() *string {
	if l == nil {
		return nil
	}
	return l.AccountID
}

func (l *LinkAccountListResponseAccountItem) GetAccountNumber() *string {
	if l == nil {
		return nil
	}
	return l.AccountNumber
}

func (l *LinkAccountListResponseAccountItem) GetAccountAddress() *string {
	if l == nil {
		return nil
	}
	return l.AccountAddress
}
