// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkConnectRequestField struct {
	FieldName  string `json:"field_name"`
	FieldValue string `json:"field_value"`
}

func (o *LinkConnectRequestField) GetFieldName() string {
	if o == nil {
		return ""
	}
	return o.FieldName
}

func (o *LinkConnectRequestField) GetFieldValue() string {
	if o == nil {
		return ""
	}
	return o.FieldValue
}
