// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkAccountListResponseAccountItem struct {
	// The account identifier
	AccountID     *string `json:"account_id,omitempty"`
	AccountNumber *string `json:"account_number,omitempty"`
	// The account's address if available
	AccountAddress *string `json:"account_address,omitempty"`
}

func (o *LinkAccountListResponseAccountItem) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}

func (o *LinkAccountListResponseAccountItem) GetAccountNumber() *string {
	if o == nil {
		return nil
	}
	return o.AccountNumber
}

func (o *LinkAccountListResponseAccountItem) GetAccountAddress() *string {
	if o == nil {
		return nil
	}
	return o.AccountAddress
}
