// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkTokenRequestResponse struct {
	// The link_token, must be provided when calling Link endpoints, for identifying the Link session.
	LinkToken string `json:"link_token"`
}

func (o *LinkTokenRequestResponse) GetLinkToken() string {
	if o == nil {
		return ""
	}
	return o.LinkToken
}
