// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type LinkConnectionStatusResponseEnum string

const (
	LinkConnectionStatusResponseEnumNew                      LinkConnectionStatusResponseEnum = "New"
	LinkConnectionStatusResponseEnumConnecting               LinkConnectionStatusResponseEnum = "Connecting"
	LinkConnectionStatusResponseEnumConnected                LinkConnectionStatusResponseEnum = "Connected"
	LinkConnectionStatusResponseEnumInvalidCredentials       LinkConnectionStatusResponseEnum = "InvalidCredentials"
	LinkConnectionStatusResponseEnumError                    LinkConnectionStatusResponseEnum = "Error"
	LinkConnectionStatusResponseEnumMfaMethodChoice          LinkConnectionStatusResponseEnum = "MfaMethodChoice"
	LinkConnectionStatusResponseEnumMfaQuestion              LinkConnectionStatusResponseEnum = "MfaQuestion"
	LinkConnectionStatusResponseEnumMfaQuestionInvalidAnswer LinkConnectionStatusResponseEnum = "MfaQuestionInvalidAnswer"
	LinkConnectionStatusResponseEnumMfaQuestionNoAnswer      LinkConnectionStatusResponseEnum = "MfaQuestionNoAnswer"
	LinkConnectionStatusResponseEnumCaptcha                  LinkConnectionStatusResponseEnum = "Captcha"
	LinkConnectionStatusResponseEnumSecurityQuestion         LinkConnectionStatusResponseEnum = "SecurityQuestion"
	LinkConnectionStatusResponseEnumAccountSelection         LinkConnectionStatusResponseEnum = "AccountSelection"
)

func (e LinkConnectionStatusResponseEnum) ToPointer() *LinkConnectionStatusResponseEnum {
	return &e
}
func (e *LinkConnectionStatusResponseEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "New":
		fallthrough
	case "Connecting":
		fallthrough
	case "Connected":
		fallthrough
	case "InvalidCredentials":
		fallthrough
	case "Error":
		fallthrough
	case "MfaMethodChoice":
		fallthrough
	case "MfaQuestion":
		fallthrough
	case "MfaQuestionInvalidAnswer":
		fallthrough
	case "MfaQuestionNoAnswer":
		fallthrough
	case "Captcha":
		fallthrough
	case "SecurityQuestion":
		fallthrough
	case "AccountSelection":
		*e = LinkConnectionStatusResponseEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LinkConnectionStatusResponseEnum: %v", v)
	}
}
