// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkConnectRequest struct {
	// The link_token, must be provided when calling Link endpoints, for identifying the Link session.
	LinkToken string `json:"link_token"`
	// Identifier of the data source to connect to.
	SourceID string `json:"source_id"`
	// List of values provided for fields specific to the selected source
	Fields []LinkConnectRequestField `json:"fields"`
	// The accepted terms of use by the end-user
	TermsOfUseURL *string `json:"terms_of_use_url,omitempty"`
	// The accepted privacy policy by the end-user
	PrivacyPolicyURL *string `json:"privacy_policy_url,omitempty"`
}

func (l *LinkConnectRequest) GetLinkToken() string {
	if l == nil {
		return ""
	}
	return l.LinkToken
}

func (l *LinkConnectRequest) GetSourceID() string {
	if l == nil {
		return ""
	}
	return l.SourceID
}

func (l *LinkConnectRequest) GetFields() []LinkConnectRequestField {
	if l == nil {
		return []LinkConnectRequestField{}
	}
	return l.Fields
}

func (l *LinkConnectRequest) GetTermsOfUseURL() *string {
	if l == nil {
		return nil
	}
	return l.TermsOfUseURL
}

func (l *LinkConnectRequest) GetPrivacyPolicyURL() *string {
	if l == nil {
		return nil
	}
	return l.PrivacyPolicyURL
}
