// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkConnectionStatusResponse struct {
	// The current status of the connection requested
	Status *LinkConnectionStatusResponseEnum `json:"status,omitempty"`
	// Additional information related to the status
	AdditionalInformation *string `json:"additional_information,omitempty"`
}

func (o *LinkConnectionStatusResponse) GetStatus() *LinkConnectionStatusResponseEnum {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *LinkConnectionStatusResponse) GetAdditionalInformation() *string {
	if o == nil {
		return nil
	}
	return o.AdditionalInformation
}
