// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type LinkTokenCreateRequestUpdateModeEnum string

const (
	LinkTokenCreateRequestUpdateModeEnumUpdateCredentials      LinkTokenCreateRequestUpdateModeEnum = "UpdateCredentials"
	LinkTokenCreateRequestUpdateModeEnumRefresh                LinkTokenCreateRequestUpdateModeEnum = "Refresh"
	LinkTokenCreateRequestUpdateModeEnumUpdateAccountSelection LinkTokenCreateRequestUpdateModeEnum = "UpdateAccountSelection"
)

func (e LinkTokenCreateRequestUpdateModeEnum) ToPointer() *LinkTokenCreateRequestUpdateModeEnum {
	return &e
}
func (e *LinkTokenCreateRequestUpdateModeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UpdateCredentials":
		fallthrough
	case "Refresh":
		fallthrough
	case "UpdateAccountSelection":
		*e = LinkTokenCreateRequestUpdateModeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LinkTokenCreateRequestUpdateModeEnum: %v", v)
	}
}
