// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MfaAnswerRequest struct {
	JobGUID *string `json:"job_guid,omitempty"`
	Answer  string  `json:"answer"`
}

func (o *MfaAnswerRequest) GetJobGUID() *string {
	if o == nil {
		return nil
	}
	return o.JobGUID
}

func (o *MfaAnswerRequest) GetAnswer() string {
	if o == nil {
		return ""
	}
	return o.Answer
}
