// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MfaAnswerRequest struct {
	JobGUID *string `json:"job_guid,omitempty"`
	Answer  string  `json:"answer"`
}

func (m *MfaAnswerRequest) GetJobGUID() *string {
	if m == nil {
		return nil
	}
	return m.JobGUID
}

func (m *MfaAnswerRequest) GetAnswer() string {
	if m == nil {
		return ""
	}
	return m.Answer
}
