// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PrepareAgentRequest struct {
	// The source GUID for the data source to warm up the agent for
	SourceGUID string `json:"source_guid"`
}

func (p *PrepareAgentRequest) GetSourceGUID() string {
	if p == nil {
		return ""
	}
	return p.SourceGUID
}
