// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Provider struct {
	// Unique identifier of the data provider associated to this connectiond
	ID *string `json:"id,omitempty"`
	// Name of the data source provider to this connection
	Name *string `json:"name,omitempty"`
}

func (p *Provider) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *Provider) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}
