// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RawDocumentRequest struct {
	// The access token associated with the Item data is being requested for
	AccessToken string `json:"access_token"`
	DocumentID  string `json:"document_id"`
}

func (r *RawDocumentRequest) GetAccessToken() string {
	if r == nil {
		return ""
	}
	return r.AccessToken
}

func (r *RawDocumentRequest) GetDocumentID() string {
	if r == nil {
		return ""
	}
	return r.DocumentID
}
