// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RawDocumentRequest struct {
	// The access token associated with the Item data is being requested for
	AccessToken string `json:"access_token"`
	DocumentID  string `json:"document_id"`
}

func (o *RawDocumentRequest) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *RawDocumentRequest) GetDocumentID() string {
	if o == nil {
		return ""
	}
	return o.DocumentID
}
