// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RefreshConnectionRequest struct {
	// The access token associated with the Item data is being requested for
	AccessToken    string   `json:"access_token"`
	AccountNumbers []string `json:"account_numbers,omitempty"`
}

func (r *RefreshConnectionRequest) GetAccessToken() string {
	if r == nil {
		return ""
	}
	return r.AccessToken
}

func (r *RefreshConnectionRequest) GetAccountNumbers() []string {
	if r == nil {
		return nil
	}
	return r.AccountNumbers
}
