// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ScreenshotData struct {
	// The URL for the screenshot itself.
	FileURL string `json:"file_url"`
	// The time the screenshot was taken.
	CreatedAt int64 `json:"created_at"`
}

func (s *ScreenshotData) GetFileURL() string {
	if s == nil {
		return ""
	}
	return s.FileURL
}

func (s *ScreenshotData) GetCreatedAt() int64 {
	if s == nil {
		return 0
	}
	return s.CreatedAt
}
