// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SecurityQuestionAnswerSaveRequest struct {
	// The link_token, must be provided when calling Link endpoints, for identifying the Link session.
	LinkToken string `json:"link_token"`
	Answer    string `json:"answer"`
}

func (s *SecurityQuestionAnswerSaveRequest) GetLinkToken() string {
	if s == nil {
		return ""
	}
	return s.LinkToken
}

func (s *SecurityQuestionAnswerSaveRequest) GetAnswer() string {
	if s == nil {
		return ""
	}
	return s.Answer
}
