// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SecurityQuestionResponse struct {
	Question string `json:"question"`
}

func (s *SecurityQuestionResponse) GetQuestion() string {
	if s == nil {
		return ""
	}
	return s.Question
}
