// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SecurityQuestionResponse struct {
	Question string `json:"question"`
}

func (o *SecurityQuestionResponse) GetQuestion() string {
	if o == nil {
		return ""
	}
	return o.Question
}
