// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	ClientID *string `security:"scheme,type=apiKey,subtype=header,name=x-deck-client-id,env=deck_client_id"`
	Secret   *string `security:"scheme,type=apiKey,subtype=header,name=x-deck-secret,env=deck_secret"`
}

func (o *Security) GetClientID() *string {
	if o == nil {
		return nil
	}
	return o.ClientID
}

func (o *Security) GetSecret() *string {
	if o == nil {
		return nil
	}
	return o.Secret
}
