// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SelectConnectionAccountsRequest struct {
	// The access token associated with the Item data is being requested for
	AccessToken string                                `json:"access_token"`
	Accounts    []GetConnectionAccountsRequestAccount `json:"accounts,omitempty"`
}

func (s *SelectConnectionAccountsRequest) GetAccessToken() string {
	if s == nil {
		return ""
	}
	return s.AccessToken
}

func (s *SelectConnectionAccountsRequest) GetAccounts() []GetConnectionAccountsRequestAccount {
	if s == nil {
		return nil
	}
	return s.Accounts
}
