// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SourceData struct {
	// The identifier of the source.
	SourceID string `json:"source_id"`
	// The name of the source.
	Name string `json:"name"`
	// The URL of the source.
	URL string `json:"url"`
	// The overridden URL of the source, if set during connection.
	TargetURL *string `json:"target_url,omitempty"`
}

func (s *SourceData) GetSourceID() string {
	if s == nil {
		return ""
	}
	return s.SourceID
}

func (s *SourceData) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SourceData) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

func (s *SourceData) GetTargetURL() *string {
	if s == nil {
		return nil
	}
	return s.TargetURL
}
