// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebhookEventTypesResponse struct {
	EventTypes []WebhookEventTypeResponse `json:"event_types"`
}

func (w *WebhookEventTypesResponse) GetEventTypes() []WebhookEventTypeResponse {
	if w == nil {
		return []WebhookEventTypeResponse{}
	}
	return w.EventTypes
}
