// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type WebhookTypeEnum string

const (
	WebhookTypeEnumLink           WebhookTypeEnum = "Link"
	WebhookTypeEnumConnection     WebhookTypeEnum = "Connection"
	WebhookTypeEnumAccounting     WebhookTypeEnum = "Accounting"
	WebhookTypeEnumBill           WebhookTypeEnum = "Bill"
	WebhookTypeEnumCreditRisk     WebhookTypeEnum = "CreditRisk"
	WebhookTypeEnumSustainability WebhookTypeEnum = "Sustainability"
	WebhookTypeEnumSwitch         WebhookTypeEnum = "Switch"
	WebhookTypeEnumIntervalData   WebhookTypeEnum = "IntervalData"
	WebhookTypeEnumJob            WebhookTypeEnum = "Job"
)

func (e WebhookTypeEnum) ToPointer() *WebhookTypeEnum {
	return &e
}
func (e *WebhookTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Link":
		fallthrough
	case "Connection":
		fallthrough
	case "Accounting":
		fallthrough
	case "Bill":
		fallthrough
	case "CreditRisk":
		fallthrough
	case "Sustainability":
		fallthrough
	case "Switch":
		fallthrough
	case "IntervalData":
		fallthrough
	case "Job":
		*e = WebhookTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebhookTypeEnum: %v", v)
	}
}
