// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebhookSubscriptionRequest struct {
	EventTypeGUID string `json:"event_type_guid"`
}

func (w *WebhookSubscriptionRequest) GetEventTypeGUID() string {
	if w == nil {
		return ""
	}
	return w.EventTypeGUID
}
