// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebhookSubscriptionRequest struct {
	EventTypeGUID string `json:"event_type_guid"`
}

func (o *WebhookSubscriptionRequest) GetEventTypeGUID() string {
	if o == nil {
		return ""
	}
	return o.EventTypeGUID
}
