// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/buildwithdeck/sdk-go/internal/utils"
	"time"
)

type WebhookEventTypeResponse struct {
	ID              string          `json:"id"`
	EventCode       string          `json:"event_code"`
	EventType       WebhookTypeEnum `json:"event_type"`
	DisplayName     string          `json:"display_name"`
	Description     string          `json:"description"`
	IsActive        *bool           `json:"is_active,omitempty"`
	DeprecatedOnUtc *time.Time      `json:"deprecated_on_utc,omitempty"`
}

func (w WebhookEventTypeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookEventTypeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"id", "event_code", "event_type", "display_name", "description"}); err != nil {
		return err
	}
	return nil
}

func (w *WebhookEventTypeResponse) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WebhookEventTypeResponse) GetEventCode() string {
	if w == nil {
		return ""
	}
	return w.EventCode
}

func (w *WebhookEventTypeResponse) GetEventType() WebhookTypeEnum {
	if w == nil {
		return WebhookTypeEnum("")
	}
	return w.EventType
}

func (w *WebhookEventTypeResponse) GetDisplayName() string {
	if w == nil {
		return ""
	}
	return w.DisplayName
}

func (w *WebhookEventTypeResponse) GetDescription() string {
	if w == nil {
		return ""
	}
	return w.Description
}

func (w *WebhookEventTypeResponse) GetIsActive() *bool {
	if w == nil {
		return nil
	}
	return w.IsActive
}

func (w *WebhookEventTypeResponse) GetDeprecatedOnUtc() *time.Time {
	if w == nil {
		return nil
	}
	return w.DeprecatedOnUtc
}
