// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebhookEventTypesResponse struct {
	EventTypes []WebhookEventTypeResponse `json:"event_types"`
}

func (o *WebhookEventTypesResponse) GetEventTypes() []WebhookEventTypeResponse {
	if o == nil {
		return []WebhookEventTypeResponse{}
	}
	return o.EventTypes
}
