// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebhookUpdateRequest struct {
	// The access token associated with the Item data is being requested for
	AccessToken string `json:"access_token"`
	// The URL of the webhook
	URL string `json:"url"`
	// The status of the webhook. If true, the webhook is active. If false, the webhook is inactive.
	IsActive bool `json:"is_active"`
}

func (o *WebhookUpdateRequest) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *WebhookUpdateRequest) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *WebhookUpdateRequest) GetIsActive() bool {
	if o == nil {
		return false
	}
	return o.IsActive
}
