// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/buildwithdeck/sdk-go/models/components"
)

type AlreadyRunningJobResponseError struct {
	// [Obsolete] Legacy identifier of the job. Use JobGuid instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	JobID string `json:"job_id"`
	// Unique identifier of the already running job.
	JobGUID string `json:"job_guid"`
	// [Obsolete] Legacy message describing the conflict. Use ErrorMessage instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Message string `json:"message"`
	// A human-readable error message indicating the job is already in progress.
	ErrorMessage string                  `json:"error_message"`
	HTTPMeta     components.HTTPMetadata `json:"-"`
}

var _ error = &AlreadyRunningJobResponseError{}

func (e *AlreadyRunningJobResponseError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
