// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/buildwithdeck/sdk-go/models/components"
)

type BadRequestJobResponseError struct {
	// A predefined error code indicating the specific reason for the failure.
	ErrorCode components.ErrorCodeEnum `json:"error_code"`
	// [Obsolete] Legacy message describing the conflict. Use ErrorMessage instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Message *string `json:"message,omitempty"`
	//  A human-readable error message indicating the job is already in progress.
	ErrorMessage string                  `json:"error_message"`
	HTTPMeta     components.HTTPMetadata `json:"-"`
}

var _ error = &BadRequestJobResponseError{}

func (e *BadRequestJobResponseError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
